version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    # Install dependencies and run tests
    docker:
      - image: cimg/python:3.11.9-node
    steps:
      - checkout
      - python/install-packages
      - run: 
          name: Install unittest-xml-reporting # esto para enteder como funciona circleCI, lo mejor seria ya tener la imagen docker con pytest
          command: pip install unittest-xml-reporting
      - run:
          name: Run tests
          command: python -m xmlrunner discover -s tests -o report || ((($? == 1)) && echo 'Did not find any tests to run.')
          environment:
              FLASK_APP: job_manager.py
      - store_test_results:
          path: report
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: build
          command: 'docker build -t jobberwocky .'
workflows:
  build-and-test:
    jobs:
      - test-python
      - build:
          requires:
            - test-python